---
- name: install mysql tools
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: ensure mysql is listening on all interfaces
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: "^bind_address"
    line: "bind-address={{ansible_eth1.ipv4.address}}"
  notify: restart mysql

- name: ensure mysql-server is started
  service: name=mysql state=started enabled=yes

- name: create demo db
  mysql_db:
    name: demo
    state: present

- name: create mysql user
  mysql_user:
    name: demo
    password: demo
    priv: 'demo.*:ALL'
    host: '%'
    state: present