---
  - hosts: lb
    become: true
    tasks:
      - name: stop lb
        service: name=nginx state=stopped
      - name: wait for lb connection on port 80 to drain
        wait_for: state=drained port=80

  - hosts: web
    become: true
    tasks:
       - name: stop web
         service: name=apache2 state=stopped
       - name: wait for web on port 80 to stop
         wait_for: state=stopped port=80

  - hosts: db
    become: true
    tasks:
       - name: restart mysql
         service: name=mysql state=restarted
       - name: wait for db on port 3306 to start
         wait_for: state=drained port=3306

  - hosts: web
    become: true
    tasks:
       - name: start apache2
         service: name=apache2 state=started
       - name: wait for apache2 on port 80 to start
         wait_for: state=started port=80

  - hosts: lb
    become: true
    tasks:
       - name: start nginx
         service: name=nginx state=started
       - name: wait for nginx on port 80 to start
         wait_for: state=started port=80