---
  - hosts: lb
    become: true
    gather_facts: false
    tasks:
      - name: verify nginx status
        command: service nginx status
      - name: verify nginx is listening on 80
        wait_for:
          port: 80
          timeout: 1

  - hosts: web
    become: true
    gather_facts: false

    tasks:
      - name: verify apache2 status
        command: service apache2 status
      - name: verify apache2 is listening on 80
        wait_for:
          port: 80
          timeout: 1

  - hosts: db
    become: true
    tasks:
      - name: verify mysql  status
        command: service mysql status
      - name: verify mysql is listening on 3306
        wait_for:
          host: "{{ansible_eth1.ipv4.address}}"
          port: 3306
          timeout: 1

  - hosts: control
    gather_facts: false
    tasks:
      - name: verify end-to-end response
        uri:
          url: http://{{item}}
          return_content: yes
        with_items: "{{groups.lb}}"
        register: lb_index

      - fail: msg="index failed to return content"
        when: "'Hello, from sunny' not in item.content"
        with_items: "{{lb_index.results}}"

  - hosts: lb
    gather_facts: false
    tasks:
      - name: verify backend response
        uri:
          url: http://{{item}}
          return_content: yes
        with_items: "{{groups.web}}"
        register: app_index

      - fail: msg="index failed to return content"
        when: item.content == "Hello, from sunny {{item.item}}!"
        with_items: "{{app_index.results}}"
