---
  - hosts: web
    become: true
    tasks:
      - import_role:
          name: apache2
      - import_role:
          name: demo_app
        vars:
          db_user_name: "{{db_user}}"
          db_user_pass: "{{db_pass}}"
          db_user_host: '%'